Module Module1

    Sub Main()

        'code -1
        Console.WriteLine(“Grass”)
        Console.WriteLine(“. . .”)
        Console.WriteLine(“ . . ”)
        Console.WriteLine(“. . .”)
        Console.WriteLine(“ . . ”)
        '0
        Console.WriteLine("Construction crane left:")
        Console.WriteLine("___|]")
        Console.WriteLine("I  | ")
        Console.WriteLine("   | ")
        Console.WriteLine("  [] ")
        '1
        Console.WriteLine("Low density residential:")
        Console.WriteLine("/\   ")
        Console.WriteLine("[]   ")
        Console.WriteLine("  /\ ")
        Console.WriteLine("  [] ")
        '2
        Console.WriteLine("High density residential:")
        Console.WriteLine("____ ")
        Console.WriteLine("[][] ")
        Console.WriteLine("[][] ")
        Console.WriteLine("[]_| ")
        '3
        Console.WriteLine("Low density commercial 1:")
        Console.WriteLine("     ")
        Console.WriteLine("_____")
        Console.WriteLine("[GAS]")
        Console.WriteLine("|  []")
        '4
        Console.WriteLine("Low density commercial 2:")
        Console.WriteLine("     ")
        Console.WriteLine("____ ")
        Console.WriteLine("MART ")
        Console.WriteLine("[]_| ")
        '5
        Console.WriteLine("High density commercial:")
        Console.WriteLine("|MA|_")
        Console.WriteLine("|LL||")
        Console.WriteLine("[][]|")
        Console.WriteLine("[][]|")
        '6
        Console.WriteLine("Small park:")
        Console.WriteLine("_____")
        Console.WriteLine("|:::|")
        Console.WriteLine("|h| |")
        Console.WriteLine("|___|")
        '7,8
        '9,10
        Console.WriteLine("Large park:")
        Console.WriteLine(" ________ ")
        Console.WriteLine("| h |.:::|")
        Console.WriteLine("|hTT|||h||")
        Console.WriteLine("|_h_||___|")
        Console.WriteLine("|___  ___|")
        Console.WriteLine("|:::|| _ |")
        Console.WriteLine("||||||/U\|")
        Console.WriteLine("|___L|___|")
        '11
        Console.WriteLine("Low vol road, horizontal:")
        Console.WriteLine("     ")
        Console.WriteLine("_____")
        Console.WriteLine("_____")
        Console.WriteLine("     ")
        '12
        Console.WriteLine("Low vol road, vertical:")
        Console.WriteLine(" ||  ")
        Console.WriteLine(" ||  ")
        Console.WriteLine(" ||  ")
        Console.WriteLine(" ||  ")
        '13
        Console.WriteLine("Low vol road 4 way junction:")
        Console.WriteLine(" ||  ")
        Console.WriteLine("/  \_")
        Console.WriteLine("_   _")
        Console.WriteLine(" \ / ")
        '14
        Console.WriteLine("Low vol road, up left right T-junction:")
        Console.WriteLine(" ||  ")
        Console.WriteLine("_/ \_")
        Console.WriteLine("_____")
        Console.WriteLine(" 	")
        '15
        Console.WriteLine("Low vol down left right t junction:")
        Console.WriteLine(" 	")
        Console.WriteLine("_____")
        Console.WriteLine("_   _")
        Console.WriteLine(" \ / ")
        '16
        Console.WriteLine("Low vol road, up down left t junction")
        Console.WriteLine(" ||  ")
        Console.WriteLine("_/|  ")
        Console.WriteLine("_ |  ")
        Console.WriteLine(" \|  ")
        '17
        Console.WriteLine("Low vol road, up down right t junction")
        Console.WriteLine(" ||  ")
        Console.WriteLine(" | \_")
        Console.WriteLine(" |  _")
        Console.WriteLine(" | / ")
        '18
        Console.WriteLine("Low vol road, up left turn:")
        Console.WriteLine(" ||  ")
        Console.WriteLine("_/|  ")
        Console.WriteLine("__/  ")
        Console.WriteLine("     ")
        '19
        Console.WriteLine("Low vol road, up right turn:")
        Console.WriteLine(" ||  ")
        Console.WriteLine(" | \_")
        Console.WriteLine(" \___")
        Console.WriteLine("     ")
        '20
        Console.WriteLine("Low vol road, down left turn:")
        Console.WriteLine("     ")
        Console.WriteLine("__   ")
        Console.WriteLine("  \  ")
        Console.WriteLine("\ |  ")
        '21
        Console.WriteLine("Low vol road, down right turn:")
        Console.WriteLine("	    ")
        Console.WriteLine("  ___")
        Console.WriteLine(" /  _")
        Console.WriteLine(" | / ")
        '22
        Console.WriteLine("Hi vol road, horizontal:")
        Console.WriteLine("_____")
        Console.WriteLine("-----")
        Console.WriteLine("_____")
        Console.WriteLine("	    ")
        '23
        Console.WriteLine("Hi vol road, vertical:")
        Console.WriteLine(" |:| ")
        Console.WriteLine(" |:| ")
        Console.WriteLine(" |:| ")
        Console.WriteLine(" |:| ")
        '24
        Console.WriteLine("Hi vol road, 4 way junction:")
        Console.WriteLine("/ : \")
        Console.WriteLine("-   -")
        Console.WriteLine(" 	")
        Console.WriteLine("\ : /")
        '25
        Console.WriteLine("Hi vol road, t-junction:")
        Console.WriteLine("_____")
        Console.WriteLine("-   -")
        Console.WriteLine(" 	")
        Console.WriteLine("\ : /")
        '26
        Console.WriteLine("Hi vol road, up left right t-junction:")
        Console.WriteLine("/ : \")
        Console.WriteLine("-   -")
        Console.WriteLine("_____")
        Console.WriteLine(" 	")
        '27
        Console.WriteLine("Hi vol road, left down up t-junction:")
        Console.WriteLine("/ : \")
        Console.WriteLine("-   -")
        Console.WriteLine(" 	")
        Console.WriteLine("\ : /")
        '28
        Console.WriteLine("Hi vol road, up left turn:")
        Console.WriteLine("/ :| ")
        Console.WriteLine("-- | ")
        Console.WriteLine("___/ ")
        Console.WriteLine(" 	")
        '29
        Console.WriteLine("Hi vol road, up right turn:")
        Console.WriteLine(" |: \")
        Console.WriteLine(" | --")
        Console.WriteLine(" \___")
        Console.WriteLine(" 	")
        '30
        Console.WriteLine("Hi vol road, down left turn:")
        Console.WriteLine("___  ")
        Console.WriteLine("-- \ ")
        Console.WriteLine("  :| ")
        Console.WriteLine("\ :| ")
        '31
        Console.WriteLine("Hi vol road, down right turn:")
        Console.WriteLine("  ___")
        Console.WriteLine(" /  -")
        Console.WriteLine(" |:  ")
        Console.WriteLine(" |: /")
        '32
        Console.WriteLine("Industrial:")
        Console.WriteLine("oOO  ")
        Console.WriteLine("__||_")
        Console.WriteLine("|   |")
        Console.WriteLine("|___|")
        '33,34
        '35,36
        Console.WriteLine("Parliament:")
        Console.WriteLine("    __    ")
        Console.WriteLine("___/  \___")
        Console.WriteLine("|[][][][]|")
        Console.WriteLine("|[][][][]|")
        Console.WriteLine("|[][][][]|")
        Console.WriteLine("|___[]___|")
        Console.WriteLine("    ||    ")
        Console.WriteLine("   /  \   ")
        '37
        Console.WriteLine("Police station:")
        Console.WriteLine("_____")
        Console.WriteLine("|POL|")
        Console.WriteLine("|ICE|")
        Console.WriteLine("|_[]|")
        '38
        Console.WriteLine("Water:")
        Console.WriteLine("~~~~~")
        Console.WriteLine("~~~~~")
        Console.WriteLine("~~~~~")
        Console.WriteLine("~~~~~")
        '39
        Console.WriteLine("Forest:")
        Console.WriteLine(":::::")
        Console.WriteLine(" | | ")
        Console.WriteLine(":::::")
        Console.WriteLine("| | |")
        '40
        Console.WriteLine("Wind farm:")
        Console.WriteLine("x   x")
        Console.WriteLine("| x |")
        Console.WriteLine("X | X")
        Console.WriteLine("|   |")
        '41
        Console.WriteLine("Coal plant")
        Console.WriteLine("OOo  ")
        Console.WriteLine(" oo  ")
        Console.WriteLine("_||__")
        Console.WriteLine("|___|")

        Console.ReadLine()
    End Sub

End Module
